services:
  app:
    container_name: app
    image: davide92/patient-manager
    environment:
      BLOB_DB_USERNAME: ${BLOB_DB_USERNAME}
      BLOB_DB_PASSWORD: ${BLOB_DB_PASSWORD}
      USER_DB_USERNAME: ${USER_DB_USERNAME}
      USER_DB_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - backend

# TODO the volume should be mounted to a specific folder in the host
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${BLOB_DB_USERNAME}
      MINIO_ROOT_PASSWORD: ${BLOB_DB_PASSWORD}
    ports:
      - "9001:9001"   # MinIO Console
    volumes:
      - minio-data:/data
    networks:
      - backend

  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: patient-manager-db
      MYSQL_USER: ${USER_DB_USERNAME}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  minio-data:
  mysql-data:

networks:
  backend:
