services:
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    networks:
      - backend

#  mysql:
#    image: mysql:8.3
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpass
#      MYSQL_DATABASE: app_db
#      MYSQL_USER: app_user
#      MYSQL_PASSWORD: app_pass
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#    networks:
#      - backend

networks:
  backend:

