spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

bucket:
  host: minio
  port: 9000
  username: ${BLOB_DB_USERNAME}
  password: ${BLOB_DB_PASSWORD}
  bucketName: my-bucket