spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://mysql:3306/patient-manager-db
    username: ${PATIENT_DB_USERNAME}
    password: ${PATIENT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

bucket:
  host: minio
  port: 9000
  username: ${BLOB_DB_USERNAME}
  password: ${BLOB_DB_PASSWORD}
  bucketName: patient-manager-bucket